language: node_js

node_js:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_b13950a340e6_key -iv $encrypted_b13950a340e6_iv -in id_rsa.enc -out /tmp/id_rsa -d

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

